inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
