#!/usr/bin/env ruby

if Dir.exist?(File.join(__dir__, "..", ".git"))
  require 'bundler/setup'
end

require 'yoda'
require 'optparse'

opt = OptionParser.new("Usage: yoda [options]") do |opt|
end

argv = opt.parse(ARGV)

case argv.first
when 'setup-deps'
  Yoda::Runner::SetupDeps.run
when 'infer'
  require 'pry'
  Pry::rescue { Yoda::Runner::Infer.run(argv[1]) }
when 'server'
  Yoda::Server.new.run
else
  puts opt.help
  exit 1
end
