name: Test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependency packages
        run: |
          sudo apt update --quiet --yes
          sudo apt install libgdbm6 libgdbm-dev
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
